default_config:

logger:
  default: debug
  logs:
    custom_components.jellyfish-lighting: debug

# If you need to debug uncomment the line below (doc: https://www.home-assistant.io/integrations/debugpy/)
debugpy:
