default_config:

logger:
  default: info
  logs:
    custom_components.jellyfish_lighting: debug

# If you need to debug uncomment the lines below (doc: https://www.home-assistant.io/integrations/debugpy/)
debugpy:
  start: true
  wait: true